# ASP.NET Framework Pipeline for AD419DataHelper
# .NET Framework 4.7 application  
# Data Loader and review website for the AD-419 Report

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet tool'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Create placeholder config files for build'
  inputs:
    targetType: 'inline'
    script: |
      # Create placeholder connectionStrings.config
      @"
      <?xml version="1.0" encoding="utf-8" ?> 
      <connectionStrings>   
        <add name="AD419DataContext" connectionString="data source=db.caes.ucdavis.edu;initial catalog=AD419_rmtest;User ID=ProdAppAD419;Password=xxxx;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
        <add name="FISDataContext" connectionString="data source=caes-elzar;initial catalog=FISDataMart;User ID=ProdAppAD419;Password=xxxx;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
        <add name="CatbertDataContext" connectionString="data source=db.caes.ucdavis.edu;initial catalog=Catbert3;User ID=ProdAppAD419;Password=xxxx;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
        <add name="PpsDataContext" connectionString="data source=caes-elzar;initial catalog=PPSDataMart;User ID=ProdAppAD419;Password=;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
      </connectionStrings>
      "@ | Out-File -FilePath "$(Build.SourcesDirectory)/AD419.DataHelper.Web/connectionStrings.config" -Encoding UTF8
      
      # Create placeholder appSettings.config
      @"
      <?xml version="1.0" encoding="utf-8"?>
      <appSettings>
        <add key="webpages:Version" value="3.0.0.0" />
        <add key="webpages:Enabled" value="false" />
        <add key="ClientValidationEnabled" value="true" />
        <add key="UnobtrusiveJavaScriptEnabled" value="true" />
        <add key="Stackify.AppName" value="AD419.DataHelper" />
        <add key="Stackify.Environment" value="localhost" />
        <add key="Stackify.ApiKey" value="[external]" />
        <add key="ReportServerUrl" value="http://reports.caes.ucdavis.edu/ReportServer/" />
        <add key="AD419AppUrl" value="https://ad419-next.caes.ucdavis.edu/" />
        <add key="ReportServerDirectory" value="/AD419Reports/" />
        <add key="InstructionsDirectory" value="~/Instructions" />
        <add key="AD419InstructionsFileName" value="AD419Instructions.pdf" />
        <add key="SqlCommandTimeout" value="30" />
        <add key="UcdProjectOrganizationName" value="CAES - UNIVERSITY OF CALIFORNIA AT DAVIS" />
        <add key="NewProjectDefaultStatus" value="Active" />
        <add key="AdminPageURL" value="https://secure.caes.ucdavis.edu/Catbert4/UserManagement/Manage/AD419" />
        <add key="ReportViewerUser" value="caes-prodapp" />
        <add key="ReportViewerPassword" value="xxxx" />
        <add key="ReportViewerDomain" value="ou" />
        <add key="Environment" value="Staging" />
      </appSettings>
      "@ | Out-File -FilePath "$(Build.SourcesDirectory)/AD419.DataHelper.Web/appSettings.config" -Encoding UTF8
      
      Write-Host "Placeholder config files created"

- task: VSBuild@1
  displayName: 'Create Web Deploy Package'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy additional web assets'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **\Views\**
      **\Content\**
      **\Scripts\**
      **\fonts\**
      **\Images\**
      **\SqlServerTypes\**
      **\*.css
      **\*.js
    TargetFolder: '$(Build.ArtifactStagingDirectory)\WebFiles'
    CleanTargetFolder: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AD419DataHelper'
    publishLocation: 'Container'

